---
output: github_document
always_allow_html: true
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# actdata

<!-- badges: start -->
<!-- badges: end -->

This package is a repository for standardized versions of publicly released affect control theory dictionaries and equations, which span nearly 45 years and many cultures worldwide. These data sets can be used by affect control theorists to understand the cultural meaning of objects and events, as well as how these meanings vary across time and place. The package also provides helper functions for subsetting, summarizing, augmenting, reformatting, and exporting these data. For information on get started with actdata, see `vignette("actdata")`.

## Affect control theory

Affect control theory is a social psychological theory of cultural meaning and interaction. In it, words have quantatively-defined meanings on three dimensions of sentiment: evaluation (good vs bad), potency (powerful vs weak), and activity (active vs passive). Affect control theory dictionaries contain these evaluation, potency, and activity (EPA) values for a variety of identities, behaviors, modifiers, and settings. Equations describe how different terms work together to create meaning in the context of events. For more information about affect control theory, see [affectcontroltheory.org](http://affectcontroltheory.org/the-theory/overview/) and the many academic resources that it links to. 

## Why actdata?

Many affect control theory data sets have been publicly released by the researchers who collected them. However, these data sets are stored in several different places and in several different formats. The actdata R package standardizes them and brings them together in one place in order to make them easier to access and make part of a reproducible analysis workflow. Details on standardization procedures for dictionaries and equation sets are located in `vignette("standardization")`.

